# Generated by Django 4.0.5 on 2022-07-27 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('j_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('discription', models.TextField(null=True, verbose_name='Discription')),
                ('photo', models.ImageField(null=True, upload_to='characters/photos', verbose_name='Photo')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MPAA_rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField(null=True, verbose_name='Discription')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('logo', models.ImageField(null=True, upload_to='studios/logos', verbose_name='Logo')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('j_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('photo', models.ImageField(null=True, upload_to='persons/photos', verbose_name='Photo')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.career', verbose_name='career')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('j_title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('discription', models.TextField(null=True, verbose_name='Discription')),
                ('rate', models.FloatField(verbose_name='Rating')),
                ('release_date', models.DateField(verbose_name='Release date')),
                ('cover', models.ImageField(null=True, upload_to='covers', verbose_name='Cover')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.person', verbose_name='Author')),
                ('category', models.ManyToManyField(to='main_app.category', verbose_name='Categories')),
                ('main_characters', models.ManyToManyField(to='main_app.character', verbose_name='Characters')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='character',
            name='voice_actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.person', verbose_name='Voice actor'),
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('j_title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('discription', models.TextField(null=True, verbose_name='Discription')),
                ('rate', models.FloatField(null=True, verbose_name='Rating')),
                ('is_out', models.BooleanField(default=False, verbose_name='Is out')),
                ('out_date', models.DateField(verbose_name='Release date')),
                ('cover', models.ImageField(null=True, upload_to='animes/covers', verbose_name='Cover')),
                ('episodes_now', models.IntegerField(verbose_name='Episodes now')),
                ('episodes_all', models.IntegerField(verbose_name='Episodes all')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('category', models.ManyToManyField(to='main_app.category', verbose_name='Categories')),
                ('main_chars', models.ManyToManyField(to='main_app.character', verbose_name='Main characters')),
                ('persons', models.ManyToManyField(to='main_app.person', verbose_name='Authors')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main_app.manga', verbose_name='Source')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.studio', verbose_name='Studio')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.type', verbose_name='Type')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
