# Generated by Django 4.0.5 on 2022-07-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('discription', models.TextField()),
                ('rate', models.FloatField()),
                ('is_out', models.BooleanField(default=False)),
                ('out_date', models.DateField(auto_now_add=True)),
                ('cover', models.ImageField(null=True, upload_to='covers/%Y/%m/%d')),
                ('category', models.ManyToManyField(to='main_app.category')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
