# Generated by Django 4.0.5 on 2022-07-22 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('logo', models.ImageField(null=True, upload_to='studios/logos', verbose_name='Logo')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes_all',
            field=models.IntegerField(verbose_name='Episodes all'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes_now',
            field=models.IntegerField(verbose_name='Episodes now'),
        ),
        migrations.AddField(
            model_name='anime',
            name='studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main_app.studio', verbose_name='Studio'),
        ),
    ]
