# Generated by Django 4.0.5 on 2022-07-22 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_studio_alter_anime_episodes_all_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.studio', verbose_name='Studio'),
        ),
    ]
