# Generated by Django 4.0.5 on 2022-08-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_person_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='synonyms',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='character',
            name='synonyms',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='manga',
            name='synonyms',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='person',
            name='synonyms',
            field=models.CharField(max_length=500),
        ),
    ]
