# Generated by Django 4.0.5 on 2022-08-27 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_anime_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='animes/covers', verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='duration',
            field=models.DurationField(default=0, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes_all',
            field=models.IntegerField(default=0, null=True, verbose_name='Episodes all'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes_now',
            field=models.IntegerField(default=0, null=True, verbose_name='Episodes now'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='out_date',
            field=models.DateField(blank=True, null=True, verbose_name='Release date'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='persons',
            field=models.ManyToManyField(blank=True, to='main_app.person', verbose_name='Authors'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main_app.manga', verbose_name='Source'),
        ),
    ]
