# Generated by Django 4.0.5 on 2022-08-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_anime_cover_alter_anime_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='synonyms',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='character',
            name='synonyms',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='manga',
            name='synonyms',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='synonyms',
            field=models.TextField(),
        ),
    ]
