# Generated by Django 4.0.5 on 2022-08-30 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_anime_synonyms_alter_character_synonyms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='type',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, to='main_app.type', verbose_name='Type'),
            preserve_default=False,
        ),
    ]
