# Generated by Django 4.0.5 on 2022-10-22 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_anime_episodes_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.manga', verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='character',
            name='photo',
            field=models.ImageField(null=True, upload_to='character/photos', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.type', verbose_name='Type'),
        ),
    ]
